# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.
# 设置主页头部的菜单信息，按weight数字排列
[[main]]
#  name = "Home"   # 菜单名称
#  url = "/"   # 对应的内容在 content/home下是哪个md
#  weight = 10

[[main]]
  name = "Documentation"
  url = "docs/"
  weight = 20

[[main]]
  name = "Blog"
  url = "blog/"
  weight = 30

[[main]]
  name = "Downloads"
  url = "https://github.com/kmesh-net/kmesh/releases"
  weight = 40

# Right Menu
[[main_right]]
  name = "<i class=\"fab fa-github\" style=\"color: #333; font-size: 1rem; line-height: 1.25\"></i>"
  post = "" # No post needed
  url = "https://github.com/kmesh-net/kmesh"
  weight = 10

[[main_right]]
  name = "<i class=\"fab fa-twitter\" style=\"color: #1DA1F2; font-size: 1rem; line-height: 1.25\"></i>"
  post = ""
  url = "https://twitter.com/Kmesh_net"
  weight = 20

[[main_right]]
  name = "<i class=\"fab fa-slack\" style=\"background: linear-gradient(to right, #36C5F0 49.9%, #2EB67D 50.1%) top, linear-gradient(to right, #E01E5A 49.9%, #ECB22E 50.1%) bottom; background-size: 100% 50%; background-repeat: no-repeat; -webkit-background-clip: text; -webkit-text-fill-color: transparent; font-size: 1rem; line-height: 1.25\"></i>"
  post = ""
  url = "https://app.slack.com/client/T08PSQ7BQ/C06BU2GB8NL"
  weight = 30

[[main_right]]
  name = "<i class=\"fab fa-weixin\" style=\"color: #1AAD19; font-size: 1rem; line-height: 1.25\"></i>"
  post = ""
  url = "https://blog.51cto.com/u_15127420/4992806"
  weight = 40

# Documentation Links
[[docs]]
  name = "Welcome"
  weight = 5
  identifier = "welcome"

[[docs]]
  name = "Architecture"
  weight = 10
  identifier = "architecture"

[[docs]]
  name = "Setup"
  weight = 15
  identifier = "setup"

[[docs]]
  name = "User Guide"
  weight = 16
  identifier = "user_guide"

[[docs]]
  name = "Performance"
  weight = 20
  identifier = "performance"

[[docs]]
  name = "Developer Guide"
  weight = 25
  identifier = "developer_guide"

[[docs]]
  name = "Community"
  weight = 30
  identifier = "community"